# Generated by Django 4.1.3 on 2023-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('trainname', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('depart', models.CharField(max_length=5)),
                ('arrival', models.CharField(max_length=5)),
                ('kms', models.IntegerField()),
                ('ec', models.IntegerField()),
                ('cc', models.IntegerField()),
            ],
        ),
    ]
