# Generated by Django 4.1.3 on 2023-03-12 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('pnr', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transactionid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('trainno', models.IntegerField()),
                ('trainname', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('kms', models.IntegerField()),
                ('classs', models.CharField(max_length=5)),
                ('doj', models.CharField(max_length=15)),
                ('amt', models.IntegerField()),
                ('passno', models.IntegerField()),
                ('list1', models.CharField(max_length=500)),
            ],
        ),
    ]
