# Generated by Django 4.1.3 on 2023-03-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='email',
            field=models.CharField(default='test@test.com', max_length=100),
        ),
    ]
